(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function t(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=t(r);fetch(r.href,o)}})();const l="44648929-0a3ca09e28beb33e491a22410";function d(e){const n=`https://pixabay.com/api/?key=${l}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(n).then(t=>{if(!t.ok)throw new Error(`HTTP error! Status: ${t.status}`);return t.json()}).then(t=>t.hits.map(s=>({webformatURL:s.webformatURL,largeImageURL:s.largeImageURL,tags:s.tags,likes:s.likes,views:s.views,comments:s.comments,downloads:s.downloads}))).catch(t=>{throw console.error("Error fetching images:",t),t})}function u(e){return`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" />
      <div class="info">
        <p><strong>Likes:</strong> ${e.likes}</p>
        <p><strong>Views:</strong> ${e.views}</p>
        <p><strong>Comments:</strong> ${e.comments}</p>
        <p><strong>Downloads:</strong> ${e.downloads}</p>
      </div>
    </a>
  `}function f(e){const n=document.getElementById("gallery");n.innerHTML=e.map(u).join("")}function g(e){e.innerHTML=""}const m=document.getElementById("search-form"),i=document.getElementById("search-input"),h=document.getElementById("gallery"),c=document.querySelector(".loader");m.addEventListener("submit",e=>{e.preventDefault();const n=i.value.trim();if(n===""){iziToast.error({message:"Please enter a search keyword."});return}g(h),y(),d(n).then(t=>{t.length===0?iziToast.info({message:"Sorry, no images matching your search query were found. Please try again!"}):(f(t),L(),i.value="")}).catch(t=>{console.error("Error loading images:",t),iziToast.error({message:"Failed to load images. Please try again later."})}).finally(()=>{p()})});function y(){c.classList.remove("hidden")}function p(){c.classList.add("hidden")}function L(){new SimpleLightbox(".gallery a",{}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
